-- Supabase PostgreSQL Schema for IT Utility Portal

-- 1. Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    parent_id BIGINT REFERENCES public.categories(id) ON DELETE CASCADE,
    icon TEXT DEFAULT 'folder',
    description TEXT,
    display_order INT DEFAULT 0
);

-- 2. Files Table
CREATE TABLE IF NOT EXISTS public.files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name TEXT NOT NULL,
    file_key TEXT UNIQUE NOT NULL,
    category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
    file_size BIGINT NOT NULL,
    sha256_hash TEXT NOT NULL,
    description TEXT,
    version TEXT,
    download_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    os_compatibility TEXT DEFAULT 'Win 10/11',
    is_portable BOOLEAN DEFAULT FALSE,
    requires_admin BOOLEAN DEFAULT TRUE
);

-- 3. Guest Passcodes Table
CREATE TABLE IF NOT EXISTS public.guest_passcodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passcode TEXT UNIQUE NOT NULL,
    label TEXT,
    max_uses INT DEFAULT 0,
    current_uses INT DEFAULT 0,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 4. File Comments / Feedback Table
CREATE TABLE IF NOT EXISTS public.file_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES public.files(id) ON DELETE CASCADE,
    author_name TEXT DEFAULT 'Technician',
    status TEXT DEFAULT 'working',
    comment_text TEXT NOT NULL,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 5. Audit Logs Table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    details TEXT,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 6. CMD / PowerShell Scripts Table
CREATE TABLE IF NOT EXISTS public.cmd_scripts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT NOT NULL,
    command TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 7. System Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- 8. Onsite Repair Checklists Table
CREATE TABLE IF NOT EXISTS public.onsite_checklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    tasks_json JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for Maximum Performance
CREATE INDEX IF NOT EXISTS idx_files_category_id ON public.files(category_id);
CREATE INDEX IF NOT EXISTS idx_files_original_name ON public.files(original_name);
CREATE INDEX IF NOT EXISTS idx_categories_parent_id ON public.categories(parent_id);
CREATE INDEX IF NOT EXISTS idx_file_comments_file_id ON public.file_comments(file_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs(created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guest_passcodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.file_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cmd_scripts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onsite_checklists ENABLE ROW LEVEL SECURITY;

-- Allow Public Read Access
CREATE POLICY "Public Read Categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Public Read Files" ON public.files FOR SELECT USING (true);
CREATE POLICY "Public Read Passcodes" ON public.guest_passcodes FOR SELECT USING (true);
CREATE POLICY "Public Read Comments" ON public.file_comments FOR SELECT USING (true);
CREATE POLICY "Public Read Audit Logs" ON public.audit_logs FOR SELECT USING (true);
CREATE POLICY "Public Read CMD Scripts" ON public.cmd_scripts FOR SELECT USING (true);
CREATE POLICY "Public Read Settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Public Read Checklists" ON public.onsite_checklists FOR SELECT USING (true);

-- Allow Public Insert for Feedback & Passcode validation
CREATE POLICY "Public Insert Comments" ON public.file_comments FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Insert Audit Logs" ON public.audit_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Passcode Counter" ON public.guest_passcodes FOR UPDATE USING (true);
